<a href="https://bmi.readthedocs.io"><img src="../../media/bmi-logo-header-text.png"></a>

# Run the `Heat` model

`Heat` models the diffusion of temperature on a uniform rectangular plate with Dirichlet boundary conditions. This is the canonical example used in the [bmi-example-python](https://github.com/csdms/bmi-example-python) repository. View the [source code](https://github.com/csdms/bmi-example-python/blob/master/heat/heat.py) for the model on GitHub.

Start by importing `numpy` and `Heat`:

In [1]:
import numpy as np
from heat.heat import Heat

Create an instance of the model, setting `shape` and `alpha` parameters:

In [2]:
n_rows = 6
n_cols = 8
conductivity = 1.0
m = Heat(shape=(n_rows,n_cols), alpha=conductivity)

Show derived parameters from the model:

In [3]:
print('Grid spacing:', m.spacing)
print('Time step:', m.time_step)

Grid spacing: (1.0, 1.0)
Time step: 0.25


What does the initial temperature field look like?

In [4]:
m.temperature = np.zeros_like(m.temperature)
print(m.temperature)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Add an impulse to the temperature field: 

In [5]:
m.temperature[3, 4] = 100.0
print(m.temperature)

[[  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 100.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


Advance the model by a single time step:

In [6]:
m.advance_in_time()

View the new state of the temperature field:

In [7]:
print(m.temperature)

[[ 0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  12.5  0.   0.   0. ]
 [ 0.   0.   0.  12.5 50.  12.5  0.   0. ]
 [ 0.   0.   0.   0.  12.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0. ]]


There's diffusion!

Advance the model to some distant time:

In [8]:
distant_time = 2.0
while m.time < distant_time:
    m.advance_in_time()

View the new state of the temperature field (with help from `np.set_printoptions`):

In [9]:
np.set_printoptions(formatter={'float': '{: 5.1f}'.format})
print(m.temperature)

[[  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0]
 [  0.0   0.2   0.9   2.1   2.8   2.1   0.9   0.0]
 [  0.0   0.7   2.2   4.7   6.2   4.7   2.1   0.0]
 [  0.0   0.9   3.0   6.1   7.9   6.1   2.8   0.0]
 [  0.0   0.6   2.0   4.1   5.3   4.1   1.8   0.0]
 [  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0]]


Note that temperature is set to zero at the boundaries.

In [10]:
m.temperature.sum()

74.10263419151306